#!/bin/sh

shift
for f
do
  if [ $num -gt 0 ]; then
    dir=`pwd | sed 's/^.*\///'`
    num=$((`awk '{if(match($0,/[0-9]+/)) print substr($0,RSTART,RLENGTH)}' ${dir}`-1))
    ln -s ../`sed 's/[0-9]+/${num}/' ${dir}`/$f .
  fi
done

